title: Mapas del Ecuador
description: Archivo digital de mapas históricos del Ecuador

theme: minima

baseurl: /mapas-del-ecuador

header_pages:
  - index.md
  - ilustraciones.md
  - mapas.md

collections:
  maps:
    output: true
    permalink: /maps/:name/
  illustrations:
    output: true
    permalink: /ilustraciones/:name/
