title: Mapas del Ecuador
description: Archivo digital de mapas históricos del Ecuador

theme: minima

baseurl: /mapas-del-ecuador

collections:
  maps:
    output: true
    permalink: /maps/:name/
  ilustraciones:
    output: true
    permalink: /ilustraciones/:name/
